### ISSUE TITLE
Improve the attack result roll template output

### ISSUE THREAD

**Issue by scooper4711** [jpmiii/Roll20harn#17]
The hover text in the grey result block can be improved.
Currently the result block shows e.g.
Attacker Gargun 4 Impact: 10
and the hover text for the 10 shows "Rolling 4 + 6 = 4+6"
Similar for the shock roll. 
It would be better if the hover text were something like "Rolling 1d6 + 6[P] = 4+6"
and the hover text for the shock roll could be something like:
"Rolling 5+6+5 < 11. FAIL"

**Comment by jpmiii** [comment]
I used the skill result roll template. We need a roll template made for this.
