### ISSUE TITLE
Bug: inventory notes on items is misaligned

### ISSUE THREAD

**Issue by scooper4711** [jpmiii/Roll20harn#5]
The notes text area is misaligned in the inventory. It is higher than the rest of the fields which increases the height of each row. 
# definition of done
* the tops and bottoms of all input fields are aligned for the inventory slots.

**Comment by scooper4711** [comment]
The issue impacts both Safari and Chrome on Mac

**Comment by jpmiii** [comment]
fixed after many hours

**Comment by scooper4711** [comment]
Much obliged!
